language: node_js
node_js:
- '6'
- '10'
script:
- yarn lint
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  api_key:
    secure: iQDTzkwChpePmXV9Jn3ljN3FhxfLKg22zuguZiNEFEFWcr5l+/tgx4LPnXYROGeUc2XMmbgaYwfDOMdFO2xo6RZsQxFXYaZrlRWTQQW8F3EHNHj5pI2f9YceBZwPy69eKtlPFuUaidCBwlJ406WLPkLyE3zHzIjuRRrC6kfm1bq2BonYwRzx2oTULr1xR7AdkUGFB8v7/ViAONhiXjYbmD/25wcNoIMp3NeUpeLAomP0MuhnmSGrToYRnsWXOx6fisTT7u9ZERllbKqikAU/uJqU23WwO/YygXJyOZcB3Uo8ImrB6UYjZadgA1HGc/y1l6lQsIDKpkS7wzx2URgL8jJ47WvX/A0NfWtg/noQT3wqIcsl4yz3nrHRJrlWWuvSkG8kNcHCAftu1I8XpkRf1HpSxNkCuofzaBrReEmYYHwsbiJ9hlwHrnX2TWpbMzv7H/Lo0+VY1apE6w3oKvsZaZjuWLMARzbWY4sRfJEWmQ5PY/loj+YBQxIVjavQbeKJeFsyjbKSPoyUeI4cB96DDJ9wivc7K0v+RwG29aRo5UTCtWnbiePPdrv11cMZO8CD4JLHDGK4Cbx6Eayeqvcv36T4j4CFuoQ8c03VbEiZ3ZDu4snBp/TKtQAMhYVYTyRjpU+LTz+sTIZJIcFkvqXAnmr+Xi5fhokXtfNpwelmFjU=
  on:
    tags: true
    repo: vega/vega-embed
    node: '10'
