language: node_js
node_js:
  - "8"
  - "10"
  - "12"
script:
  - yarn lint
  - yarn test
  - yarn build
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: domoritz@gmail.com
  on:
    tags: true
    repo: vega/vega-embed
    node: "12"
  api_key:
    secure: s5T8DsPwoeYP4v4DAHZFI63DOP/5Jt3GsxJRMzsxRjIJKtjHHvA9oD/tdo1GRobu5bEhRR8hBNCpW1BlQlEtraciWEP5WxBbr5lhcatkIlNPp6isqJa3IlPGJdG3aF+v2m4/WTFQqCmkS7u+H2fpoavI5xn1dvLRowSiFG5N16SNMGd1FLkxqd8PyaRxPvy+uY+qOSymTSb9MBhOmHo+OPSG64SYjQNDilD/Dd4AocIWd42kATV7aCfqcRPO0oIGqteXAqm1dmqLFGG5T+YZpw2YIDq+0MTTX9vXRhbIDtGG+5mmkSCgzcgKJHospBWFBfsz2beYgMAjAtsP9dSEm7YBElzegHdyw3iYwGxKXtuUVnOttvZbATWLbn1bOmsBwwyB6gMnT4j+5k6iDmjLQ+rhGnBz1lvSpZlhuLQ7xk1/iWTm12YvnpL1SPjrH4aYD5nIlp2Eyngp0jN7aUBGgK9zHij/lzboyz0QNKShaWKx1Ym93HVk1xLKcXUrpYGdlpLjEhr+hXJURNybEM1WoI4WnMgFBqgpPc0w/WYcdDTNXUCia3ezfonjy9GtBBgeHKmMCoog9HTCIdcbd1jTMS1osVb8IQeb+Cn/2rA99gBapDGOabLJu6U1cEwpzjzZi4k+pHNXJ+9QqexCFRlwAAq46ByMtxXKxz6V/BuRqFE=
