name: Publish

on:
  push:
    branches-ignore:
      # No canary deploys for branches opened by dependabot
      - "dependabot/**"

jobs:
  publish:
    name: Make a release and publish to NPM

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "16"

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      # don't use yarn run to avoid using yarnpkg registry
      - name: Create release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
